name: AdminChat
main: tc.oc.adminchat.AdminChat
version: ${project.version}
author: Overcast Network

depend: [Channels]

permissions:
  chat.admin:
    description: Allows sending and receiving of admin chat messages.
    default: op
    children:
      chat.admin.send:
        description: Allows sending of admin chat messages
      chat.admin.receive:
        description: Allows receiving of admin chat messages
